### ISSUE TITLE
Weird stacktrace issue when linking to raylib.

### ISSUE THREAD

**Issue by realaltffour** [ryupold/raylib.zig#1] opened 2022-07-08 10:05 UTC
Using the example project provided, and following zig's memory leak example causes weird stack trace issues.

![image](https://user-images.githubusercontent.com/56314286/177970178-2b07f687-ec43-4f6b-a8e9-8e7ff4bda277.png)

**Comment by ryupold** [comment] 2022-07-08 10:13
Can you elaborate which example you did run to end up with that error?
I ran examples 1-10 (from examples-raylib.zig) on windows/mac with 0.9.1 and the current master and did not encounter this problem.

**Comment by realaltffour** [comment] 2022-07-08 10:28
I meant to say that I used the example build.zig not the examples themselves.

For the code that causes the issue:
```
pub fn main() !void {
    var testMap =
        \\#www#www#wwwwww#
        \\w...w.w.w.w....w
        \\w.pb..d.w...w..w
        \\w.......w......w
        \\w.......w......w
        \\wwwwwwwwwwwwwwww
        \\
    ;

    var general_purpose_allocator = std.heap.GeneralPurposeAllocator(.{}){};
    const alloc = general_purpose_allocator.allocator();

    var gameMap = try alloc.alloc(u8, testMap.len);
    std.mem.copy(u8, gameMap, testMap);

    _ = general_purpose_allocator.deinit();
}
```

and build.zig
```
    const exe = b.addExecutable("zigample", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);

    const raylibSrc = "src/raylib/raylib/src/";
    const bindingSrc = "src/raylib/";
    const rayBuild = @import("src/raylib/raylib/src/build.zig");
    const raylib = rayBuild.addRaylib(b, target);
    exe.linkLibrary(raylib);
    exe.addIncludeDir(raylibSrc);
    exe.addIncludeDir(raylibSrc ++ "extras/");
    exe.addIncludeDir(bindingSrc);
    exe.addCSourceFile(bindingSrc ++ "marshal.c", &.{});

    exe.linkLibC();
    exe.install();
```

**Comment by ryupold** [comment] 2022-07-09 13:35
Thank you very much for finding the cause of the problem.
Can I do something to prevent that happening? In my understanding raylib needs the X11/GLFW libraries to show the window.
Do I understand it right, that this has rather to do with os/machine specific problems in combination with X11 and I can close the issue?

I also could not reproduce the issue on my linux machine (fedora 35). I get a nice looking stacktrace.

**Comment by realaltffour** [comment] 2022-07-10 14:24
> Do I understand it right, that this has rather to do with os/machine specific problems in combination with X11 and I can close the issue?

Yes, related to DWARFv5 generation from zig .

> I also could not reproduce the issue on my linux machine (fedora 35). I get a nice looking stacktrace.

It appears to be happening with certain libraries/combination of libraries, nothing specific to this project afaik.

Hopefully this thread helps someone out there!

**Closed** 2022-07-10 14:24 UTC
